### ISSUE TITLE
Update to tokio1.0.0?

### ISSUE THREAD

**Issue by sMitea** [sunng87/rustmann#17]

**Comment by sunng87** [comment]
It's a work in progress. We are blocked on prost to release a new version with bytes 1.0. Now it seems the new version is available. I will push my branch later today.

**Comment by sMitea** [comment]
Thank you.

**Comment by sunng87** [comment]
@sMitea btw are you using this library in any of your projects?

**Comment by sMitea** [comment]
Yes, this is my project's [link](http://bx.enmotech.com/).

**Comment by sunng87** [comment]
0.7 has been pushed to crates.io for tokio 1.0
